<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.codingmatters.poom</groupId>
        <artifactId>poom-services</artifactId>
        <version>1.272.0</version>
    </parent>

    <groupId>org.codingmatters.poom.stacks</groupId>
    <artifactId>poom-stacks</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Poor Man's Stacks</name>
    <url>https://github.com/flexiooss/poom-stacks</url>


    <modules>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.codingmatters.poom</groupId>
            <artifactId>poom-services-logging</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!--BOM-->
            <!--// BOM-->
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
            </plugins>
        </pluginManagement>
    </build>


    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>


    <scm>
        <connection>scm:git:git@github.com:flexiooss/poom-stacks</connection>
        <developerConnection>scm:git:git@github.com:flexiooss/poom-stacks.git</developerConnection>
        <url>git@github.com:flexiooss/poom-stacks.git</url>
    </scm>

    <repositories>
        <repository>
            <id>codingmatters-snapshots</id>
            <url>https://mvn.ci.flexio.io/codingmatters-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>codingmatters-releases</id>
            <url>https://mvn.ci.flexio.io/codingmatters-releases/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>codingmatters-snapshots</id>
            <url>https://mvn.ci.flexio.io/codingmatters-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>codingmatters-releases</id>
            <url>https://mvn.ci.flexio.io/codingmatters-releases/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

</project>
